[project]
name = 'microsponsor'
description = 'Decentralized micro-scholarship platform'
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []

[contracts.stxmicrosponsor]
path = 'contracts/stxmicrosponsor.clar'
clarity_version = 3
epoch = 3.0
